spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=YourDatabaseName;encrypt=true;trustServerCertificate=true
    username: YourUserName
    password: YourPassword
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
