INSERT INTO roles (name) VALUES ('USER');
INSERT INTO roles (name) VALUES ('ADMIN');

INSERT INTO categories (id, name) VALUES ('b33a815e-7da0-53b5-9f2b-b8055a1d9bbe', N'Âm nhạc và Mỹ thuật')
INSERT INTO categories (id, name) VALUES ('1e600e93-8a53-55f4-a859-9fcda07fbc55', N'Công nghệ')
INSERT INTO categories (id, name) VALUES ('aa376bfd-6103-59a9-826c-c1fff0abcbd7', N'Kinh tế')
INSERT INTO categories (id, name) VALUES ('e2855c0c-a5e4-5bec-8c20-e2346b3bea19', N'Chính trị')
INSERT INTO categories (id, name) VALUES ('60e2d797-329e-558c-afa7-756b3965f671', N'Lịch sử')
INSERT INTO categories (id, name) VALUES ('bbf2a6ee-c776-56bd-ae8f-1b2a8f0e012e', N'Văn hóa và Xã hội')
INSERT INTO categories (id, name) VALUES ('4efed178-a654-5461-8686-db287fe7dde7', N'Y tế và Sức khỏe')
INSERT INTO categories (id, name) VALUES ('da78c65b-9f8b-56d2-9185-18c83e66361a', N'Khoa học viễn tưởng')
INSERT INTO categories (id, name) VALUES ('dac3b0d5-9d4e-592d-b84b-777d9f1c0c80', N'Thiếu nhi')
INSERT INTO categories (id, name) VALUES ('682525b4-1dd9-5e3f-b96c-616a1c56359e', N'Trinh thám')
INSERT INTO categories (id, name) VALUES ('d85e5fa6-7c9d-53db-92ef-b1ad2faa28bc', N'Tiểu thuyết')
INSERT INTO categories (id, name) VALUES ('a39d61d9-7081-5f40-820c-1283cb71595e', N'Truyện ngắn')
INSERT INTO categories (id, name) VALUES ('27d33872-8380-5663-b700-94d451163e20', N'Truyện cười')

INSERT INTO authors (id, name, year_of_birth, nationality, image_url, biography) VALUES ('b0485a4e-0c63-5d49-bf09-5ebdb1aade17', N'J.K. Rowling', '1965', N'Anh', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/1280px-J._K._Rowling_2010.jpg', N'<p>Joanne Rowling, thường được biết đến với bút danh J. K. Rowling, là một nhà văn, nhà từ thiện, nhà sản xuất phim và truyền hình, nhà biên kịch người Anh. Bà nổi tiếng là tác giả của bộ truyện giả tưởng Harry Potter từng đoạt nhiều giải thưởng và bán được hơn 500 triệu bản, trở thành bộ sách bán chạy nhất trong lịch sử. Bộ sách đã được chuyển thể thành một loạt phim ăn khách mà chính bà đã phê duyệt kịch bản và cũng là nhà sản xuất của hai phần cuối. Bà cũng viết tiểu thuyết trinh thám hình sự dưới bút danh Robert Galbraith.</p>');
INSERT INTO authors (id, name, year_of_birth, nationality, image_url, biography) VALUES ('b2bdae27-78a3-5ca5-916e-9bb0fa7dd7d2', N'Steve McConnell', '1962', N'Mỹ', 'https://stevemcconnell.com/wp-content/uploads/2020/10/SteveMcConnell-M.jpg', N'<p>Steve McConnell, tác giả và kỹ sư phần mềm nổi tiếng, sinh năm 1962 tại Hoa Kỳ. Ông có bằng cử nhân triết học và thạc sĩ kỹ thuật phần mềm.</p><p>McConnell được biết đến với nhiều sách giáo khoa về kỹ thuật phần mềm và quản lý dự án, bao gồm "Code Complete", "Rapid Development", và "Software Estimation". Các tác phẩm của ông được sử dụng rộng rãi và ông là diễn giả thường xuyên tại các hội nghị về kỹ thuật phần mềm.</p><p>McConnell được coi là chuyên gia hàng đầu trong lĩnh vực này, nhận được nhiều giải thưởng cho các tác phẩm của mình. Ông là thành viên của ACM và IEEE, từng giảng dạy tại Đại học Seattle và Carnegie Mellon, và là nhà tư vấn cho nhiều công ty phần mềm lớn.</p>');
INSERT INTO authors (id, name, year_of_birth, nationality, image_url, biography) VALUES ('a663b778-f9bc-59f3-958c-353db513d9d9', N'Robert C. Martin', '1955', N'Mỹ', 'https://files.gotocon.com/uploads/portraits/161/square_medium/robert%20c._martin%20(uncle%20bob)_1548158817.png', N'<p>Robert Cecil Martin, thường được gọi là "Uncle Bob", là một kỹ sư phần mềm, tác giả và nhà tư vấn người Mỹ. Ông sinh năm 1952 tại Palo Alto, California.</p><p>Martin được công nhận rộng rãi bởi những đóng góp cho lĩnh vực kỹ thuật phần mềm. Ông là người sáng lập ra nhiều nguyên tắc thiết kế phần mềm và là tác giả của nhiều cuốn sách nổi tiếng, bao gồm "Clean Code", "Agile Principles, Patterns, and Practices", và "Uncle Bob''s Principles of Object-Oriented Design".</p><p>Với hơn 40 năm kinh nghiệm trong ngành, Martin là chuyên gia được kính trọng trong cộng đồng phát triển phần mềm. Ông thường xuyên diễn thuyết tại các hội nghị và hội thảo, đồng thời cung cấp dịch vụ tư vấn cho các tổ chức trên toàn thế giới.</p>');
INSERT INTO authors (id, name, year_of_birth, year_of_death, nationality, image_url, biography) VALUES ('483a235a-ac1b-5333-99bd-6d683c425c8d', N'Ngô Tất Tố', '1893', '1954', N'Việt Nam', 'https://upload.wikimedia.org/wikipedia/vi/thumb/9/92/NgoTatTo.jpg/175px-NgoTatTo.jpg', N'<p>Ngô Tất Tố (1893 - 1954) là một nhà văn, nhà báo, nhà Nho học, dịch giả và nhà nghiên cứu nổi tiếng của Việt Nam. Ông sinh ra tại làng Lộc Hà, tổng Hội Phụ, phủ Từ Sơn, tỉnh Bắc Ninh (nay thuộc Đông Anh, ngoại thành Hà Nội).</p><p>Ngô Tất Tố xuất thân là một nhà nho nhưng sớm tiếp thu tư tưởng mới và tham gia hoạt động cách mạng.</p><p>Ông là một nhà văn hiện thực xuất sắc, chuyên viết về đề tài nông thôn Việt Nam trước Cách mạng tháng Tám.</p><p>Các tác phẩm của ông phản ánh chân thực cuộc sống của người nông dân, tố cáo xã hội phong kiến thối nát và thể hiện niềm tin vào tương lai tươi sáng.</p>');
INSERT INTO authors (id, name, year_of_birth, year_of_death, nationality, image_url, biography) VALUES ('d16d993d-cbad-5bdc-a138-7a5b4b3ea8d6', N'Hồ Chí Minh', '1890', '1969', N'Việt Nam', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Ho_Chi_Minh_1946.jpg/220px-Ho_Chi_Minh_1946.jpg', N'<p>Chủ tịch Hồ Chí Minh, tên khai sinh là Nguyễn Sinh Cung, sinh ngày 19 tháng 5 năm 1890 tại làng Kim Liên, Nghệ An. Lớn lên trong cảnh nước mất nhà tan, Người sớm nung nấu ý chí cứu nước. Năm 1911, Người ra đi tìm đường cứu nước, trải qua hơn 30 năm bôn ba khắp năm châu bốn biển, tìm hiểu về các cuộc cách mạng trên thế giới và sáng lập ra Đảng Cộng sản Việt Nam. Dưới sự lãnh đạo của Người, nhân dân Việt Nam đã tiến hành Cách mạng tháng Tám năm 1945, giành lại độc lập dân tộc. Sau đó, Người lãnh đạo nhân dân Việt Nam chiến thắng thực dân Pháp và đế quốc Mỹ, thống nhất đất nước.</p><p>Chủ tịch Hồ Chí Minh là vị lãnh tụ vĩ đại của dân tộc Việt Nam, Anh hùng giải phóng dân tộc, danh nhân văn hóa thế giới. Người đã dành cả cuộc đời cho sự nghiệp giải phóng dân tộc, thống nhất đất nước và xây dựng đất nước Việt Nam. Di sản của Người là Tư tưởng Hồ Chí Minh và một Việt Nam độc lập, thống nhất, giàu mạnh.</p><p>Chủ tịch Hồ Chí Minh là tấm gương sáng về lòng yêu nước, tinh thần dũng cảm, hy sinh và đạo đức cách mạng. Người là nguồn cảm hứng cho các thế hệ người Việt Nam tiếp tục xây dựng đất nước ngày càng giàu mạnh.</p>');
INSERT INTO authors (id, name, year_of_birth, nationality, image_url, biography) VALUES ('7e9fd68a-ba92-5ddf-bfa2-471f55b60a4a', N'Michael Pollan', '1955', N'Mỹ', 'https://pbs.twimg.com/profile_images/2992761845/bc2f1ddf99da4c777b98768be883078e_400x400.jpeg', N'<p>Michael Pollan, sinh năm 1955, là một nhà báo, nhà văn và nhà hoạt động môi trường người Mỹ. Ông nổi tiếng với các tác phẩm về thực phẩm, nông nghiệp và môi trường, kết hợp khoa học, triết học và lịch sử.</p><p>Pollan tốt nghiệp Đại học Columbia và Đại học Oxford, bắt đầu sự nghiệp viết lách với các bài báo cho Harper''s Magazine và The New York Times Magazine. Cuốn sách đầu tay "Second Nature: A Gardener''s Education" xuất bản năm 1991 đã trở thành bestseller. Ông tiếp tục viết nhiều cuốn sách về thực phẩm và nông nghiệp như "The Omnivore''s Dilemma", "In Defense of Food" và "Cooked", được dịch ra hơn 20 ngôn ngữ và nhận được nhiều giải thưởng.</p><p>Pollan được coi là nhà văn có ảnh hưởng nhất về thực phẩm và nông nghiệp, góp phần nâng cao nhận thức về tác động của hệ thống thực phẩm công nghiệp đối với sức khỏe con người và môi trường. Ông cũng là nhà hoạt động tích cực cho các phong trào nông nghiệp bền vững và thực phẩm địa phương.</p>');
INSERT INTO authors (id, name, year_of_birth, nationality, image_url, biography) VALUES ('c0bd5e99-dafa-5be4-a8ee-21c29973b2ca', N'Mark Bittman', '1955', N'Mỹ', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Mark_Bittman_2017.jpg', N'<p>Mark Bittman là nhà báo, tác giả và cựu chuyên gia ẩm thực của tờ The New York Times. Ông nổi tiếng với việc đề xuất chế độ ăn uống VB6 linh hoạt, tập trung vào thực vật và hạn chế thịt.</p><p>Sinh năm 1950 tại Manhattan, New York, Bittman theo học Đại học Clark và bắt đầu sự nghiệp viết lách về thực phẩm vào đầu những năm 1980. Ông là tác giả của hơn 20 cuốn sách, bao gồm "How to Cook Everything", "The VB6 Cookbook" và "Food Matters". Bittman cũng từng dẫn chương trình nấu ăn trên truyền hình và là người sáng lập trang web Gilt Taste.</p><p>Với hơn 30 năm kinh nghiệm trong ngành ẩm thực, Bittman được coi là chuyên gia uy tín về thực phẩm và dinh dưỡng. Ông ủng hộ lối sống ăn uống lành mạnh, bền vững và tập trung vào thực vật. Bittman tin rằng chế độ ăn uống cân bằng, đầy đủ dinh dưỡng có thể giúp cải thiện sức khỏe và bảo vệ môi trường.</p>');